config/routes.rb
MarchMadness::Application.routes.draw do

  resources :pools do
    resources :entries
  end

  resources :entries do
    resources :picks
  end

  resources :pools do
    resources :teams
  end

  match '/pools/:id/entries/calculate' => 'entries#calculate'

  root :to => 'pools#index'

end

app/models/pool.rb
class Pool < ActiveRecord::Base
  attr_accessible :poolname, :teams_attributes

  has_many :teams, :dependent => :destroy
  accepts_nested_attributes_for :teams#, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

  has_many :entries , :dependent => :destroy
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  def index
    @pools = Pool.all
  end
  
  def show
    @pool = Pool.find(params[:id])
  end
  
  def new
    @pool = Pool.new
    64.times { @pool.teams.build }
  end
  
  def create
    @pool = Pool.new(params[:pool])
    if @pool.save
      flash[:notice] = "Successfully created pool."
      redirect_to @pool
    else
      render :action => 'new'
    end
  end
  
  def edit
    @pool = Pool.find(params[:id])
  end
  
  def update
    @pool = Pool.find(params[:id])
    if @pool.update_attributes(params[:pool])
      flash[:notice] = "Successfully updated pool."
      redirect_to @pool
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @pool = Pool.find(params[:id])
    @pool.destroy
    flash[:notice] = "Successfully destroyed pool."
    redirect_to pools_url
  end
end

app/helpers/pool_helper.rb
module PoolHelper
end

app/views/pools/_form.html.erb
<%= form_for @pool do |f| %>
  <% if @pool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pool.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @pool.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :poolname %><br />
    <%= f.text_field :poolname %>
  </div>
  <% i = 0 %>
  <%= f.fields_for :teams do |builder| %>
    <%= render "team_fields", { :f => builder, :i => i } %>
    <% i += 1 %>
  <% end %>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/pools/_team_fields.html.erb
<p>
  <%= f.label :name, "Team " %>
  <%= f.number_field :game, :value => i.to_i %>
  <%= f.text_field :name %>
</p>

app/views/pools/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @pool %> |
<%= link_to "Back to Pools", pools_path %>

app/views/pools/index.html.erb
<%= stylesheet_link_tag "pools" %>

<h1>Listing Pools</h1>

<table>
  <tr>
    <th>Pool Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pools.each do |pool| %>
  <tr>
    <td><a href=<%= pool_entries_path(pool) %>><%= pool.poolname %></a>
    <td><%= link_to 'Show', pool_teams_path(pool) %></td>
    <td><%= link_to 'Edit', edit_pool_path(pool) %></td>
    <td><%= link_to 'Destroy', pool, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pool', new_pool_path %>

app/views/pools/new.html.erb
<h1>New Pool</h1>

<%= render 'form' %>

<%= link_to 'Back', pools_path %>

app/views/pools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Poolname:</b>
  <%= @pool.poolname %>
</p>

<%= link_to "Back", pools_path %>