config/routes.rb
MarchMadness::Application.routes.draw do

  resources :pools do
    resources :entries
  end

  resources :entries do
    resources :picks
  end

  resources :pools do
    resources :teams
  end

  match '/pools/:id/entries/calculate' => 'entries#calculate'

  root :to => 'pools#index'

end

app/models/pick.rb
class Pick < ActiveRecord::Base
  attr_accessible :game, :pick, :round

  belongs_to :entry
  #belongs_to :pool
  #belongs_to :pickable, :polymorphic => true

  validates_uniqueness_of :game, :scope => [:round, :pick, :entry_id]

  def samePick?(other)
    if !other.nil? && !other.pick.nil? && !:pick.nil?
      if other.pick == :pick
        return true
      end
    end
    return false
  end
end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
  before_filter :load_pool_entry

  # GET /entries
  # GET /entries.json
  def index
    @picks_array = @entry.picks.all
    @picks = Hash.new
    @picks_array.each do |pick|
      round = pick.round
      add = 0
      for i in 1...round
        add += 2 ** (6-i)
      end
      @picks[pick.game + add] = pick
    end
    @teams = @pool.teams

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @picks }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @picks = @entry.picks.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picks }
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new
    @pick = @entry.picks.new
    @pick.game = params[:game]
    @pick.round = params[:round]
    @pick.pick = params[:pick]
    @entry.picks.each do |p|
      if p.game == @pick.game && p.round.to_i == @pick.round.to_i && p.pick != @pick.pick
        {:controller => 'picks', :action => 'destroy', :id => p.id}
      end
    end
    @pick.save
    redirect_to :action => 'index'
    #respond_to do |format|
      #format.html # new.html.erb
      #format.json { render json: @pick }
    #end
  end

  # GET /entries/1/edit
  def edit
    @pick = @entry.picks.find(params[:id])
    @pick.pick = params[:pick]
  end

  # POST /entries
  # POST /entries.json
  def create
    @pick = @entry.picks.new(params[:pick])

    respond_to do |format|
      if @pick.save
        format.html { redirect_to [@entry,@pick], notice: 'Entry was successfully created.' }
        format.json { render json: @pick, status: :created, location: @pick }
      else
        format.html { render action: "new" }
        format.json { render json: @pick.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    @pick = @entry.picks.find(params[:id])

    respond_to do |format|
      if @pick.update_attributes(params[:entry])
        format.html { redirect_to [@entry,@pick], notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pick.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @pick = @entry.picks.find(params[:id])
    @pick.destroy
    logger.debug("destroy")

    respond_to do |format|
      format.html { redirect_to [@pool,@entry] }
      format.json { head :no_content }
    end
  end

  private

  def load_pool_entry
    @entry = Entry.find(params[:entry_id])
    @pool = Pool.find(@entry.pool_id)
    @master = @pool.entries.find_by_entryname("Master")

    if @master.nil?
      redirect_to new_pool_entry_path(@pool)
    else

      # Convert Master picks to hash
      @mPicks = Hash.new
      @master.picks.all.each do |pick|
        round = pick.round
        add = 0
        for i in 1...round
          add += 2 ** (6-i)
        end
        @mPicks[pick.game + add] = pick
      end
    end
  end
end

app/helpers/pick_helper.rb
module PickHelper
end

app/views/picks/entry.html.erb
<h1>Edit</h1>

app/views/picks/index.html.erb
<%= stylesheet_link_tag "picks" %>

<h1><%= @entry.entryname %> Picks</h1>

<table>
<% for rownum in 0..63 %>
  <% index = rownum %>
  <tr>
  <% if rownum % 2 == 0 %>
    <td class=game><%= link_to @teams[index/2].name, new_entry_pick_path(@entry, { :pick => @teams[index/2].name, :round => 0 + 1, :game => @teams[index/2].game / 2 } ) %></td>
    <td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td>
    <td class=game><%= link_to @teams[(index/2)+32].name, new_entry_pick_path(@entry, { :pick => @teams[(index/2)+32].name, :round => 0 + 1, :game => @teams[(index/2)+32].game / 2 } ) %></td>
  <% elsif (rownum-1) % 4 == 0 %>
    <td></td>
      <% @leftPick = @picks[(index/4)] %>
      <% @mpick = @mPicks[(index/4)] %>
      <% if @leftPick.nil? %>
        <td class=game id=wrong><%= "&nbsp;".html_safe %></td>
      <% else %>
        <td class=game 
          <% if !@mpick.nil? %>
            <% if @leftPick.pick == @mpick.pick %>
              <%= 'id=correct' %>
            <% else %>
              <%= 'id=wrong' %>
            <% end %>
          <% end %>
        >
        <%= link_to @leftPick.pick, new_entry_pick_path(@entry, { :pick => @leftPick.pick, :round => @leftPick.round + 1, :game => @leftPick.game / 2 } ) %>
        </td>
      <% end %>
    <td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td>
      <% @rightPick = @picks[(index/4)+16] %>
      <% @mpick = @mPicks[(index/4)+16] %>
      <% if @rightPick.nil? %>
        <td class=game id=wrong><%= "&nbsp;".html_safe %></td>
      <% else %>
        <td class=game
          <% if !@mpick.nil? %>
            <% if @rightPick.pick == @mpick.pick %>
              <%= 'id=correct' %>
            <% else %>
              <%= 'id=wrong' %>
            <% end %>
          <% end %>
        >
        <%= link_to @rightPick.pick, new_entry_pick_path(@entry, { :pick => @rightPick.pick, :round => @rightPick.round + 1, :game => @rightPick.game / 2 } ) %>
        </td>
      <% end %>
    <td></td>
  <% elsif (rownum-3) % 8 == 0 %>
    <td></td><td></td>
      <% @leftPick = @picks[(index/8)+32] %>
      <% @mpick = @mPicks[(index/8)+32] %>
      <% if @leftPick.nil? %>
        <td class=game id=wrong><%= "&nbsp;".html_safe %></td>
      <% else %>
        <td class=game
          <% if !@mpick.nil? %>
            <% if @leftPick.pick == @mpick.pick %>
              <%= 'id=correct' %>
            <% else %>
              <%= 'id=wrong' %>
            <% end %>
          <% end %>
        >
        <%= link_to @leftPick.pick, new_entry_pick_path(@entry, { :pick => @leftPick.pick, :round => @leftPick.round + 1, :game => @leftPick.game / 2 } ) %>
        </td>
      <% end %>
    <td></td><td></td><td></td><td></td><td></td><td></td><td></td>
      <% @rightPick = @picks[(index/8)+32+8] %>
      <% @mpick = @mPicks[(index/8)+32+8] %>
      <% if @rightPick.nil? %>
        <td class=game id=wrong><%= "&nbsp;".html_safe %></td>
      <% else %>
        <td class=game
          <% if !@mpick.nil? %>
            <% if @rightPick.pick == @mpick.pick %>
              <%= 'id=correct' %>
            <% else %>
              <%= 'id=wrong' %>
            <% end %>
          <% end %>
        >
        <%= link_to @rightPick.pick, new_entry_pick_path(@entry, { :pick => @rightPick.pick, :round => @rightPick.round + 1, :game => @rightPick.game / 2 } ) %>
        </td>
      <% end %>
    <td></td><td></td>
  <% elsif (rownum-7) % 16 == 0 %>
    <td></td><td></td><td></td>
      <% @leftPick = @picks[(index/16)+48] %>
      <% @mpick = @mPicks[(index/16)+48] %>
      <% if @leftPick.nil? %>
        <td class=game id=wrong><%= "&nbsp;".html_safe %></td>
      <% else %>
        <td class=game
          <% if !@mpick.nil? %>
            <% if @leftPick.pick == @mpick.pick %>
              <%= 'id=correct' %>
            <% else %>
              <%= 'id=wrong' %>
            <% end %>
          <% end %>
        >
        <%= link_to @leftPick.pick, new_entry_pick_path(@entry, { :pick => @leftPick.pick, :round => @leftPick.round + 1, :game => @leftPick.game / 2 } ) %>
        </td>
      <% end %>
    <td></td><td></td><td></td><td></td><td></td>
      <% @rightPick = @picks[(index/16)+48+4] %>
      <% @mpick = @mPicks[(index/16)+48+4] %>
      <% if @rightPick.nil? %>
        <td class=game id=wrong><%= "&nbsp;".html_safe %></td>
      <% else %>
        <td class=game
          <% if !@mpick.nil? %>
            <% if @rightPick.pick == @mpick.pick %>
              <%= 'id=correct' %>
            <% else %>
              <%= 'id=wrong' %>
            <% end %>
          <% end %>
        >
        <%= link_to @rightPick.pick, new_entry_pick_path(@entry, { :pick => @rightPick.pick, :round => @rightPick.round + 1, :game => @rightPick.game / 2 } ) %>
        </td>
      <% end %>
    <td></td><td></td><td></td>
  <% elsif (rownum-15) % 32 == 0 %>
    <td></td><td></td><td></td><td></td>
      <% @leftPick = @picks[(index/32)+56] %>
      <% @mpick = @mPicks[(index/32)+56] %>
      <% if @leftPick.nil? %>
        <td class=game id=wrong><%= "&nbsp;".html_safe %></td>
      <% else %>
        <td class=game
          <% if !@mpick.nil? %>
            <% if @leftPick.pick == @mpick.pick %>
              <%= 'id=correct' %>
            <% else %>
              <%= 'id=wrong' %>
            <% end %>
          <% end %>
        >
        <%= link_to @leftPick.pick, new_entry_pick_path(@entry, { :pick => @leftPick.pick, :round => @leftPick.round + 1, :game => @leftPick.game / 2 } ) %>
        </td>
      <% end %>
    <td></td><td></td><td></td>
      <% @rightPick = @picks[(index/32)+56+2] %>
      <% @mpick = @mPicks[(index/32)+56+2] %>
      <% if @rightPick.nil? %>
        <td class=game id=wrong><%= "&nbsp;".html_safe %></td>
      <% else %>
        <td class=game
          <% if !@mpick.nil? %>
            <% if @rightPick.pick == @mpick.pick %>
              <%= 'id=correct' %>
            <% else %>
              <%= 'id=wrong' %>
            <% end %>
          <% end %>
        >
        <%= link_to @rightPick.pick, new_entry_pick_path(@entry, { :pick => @rightPick.pick, :round => @rightPick.round + 1, :game => @rightPick.game / 2 } ) %>
        </td>
      <% end %>
    <td></td><td></td><td></td><td></td>
  <% elsif (rownum-31) % 64 == 0 %>
    </tr><tr><td>&nbsp;<td></tr><tr>
    <td></td><td></td><td></td><td></td><td></td>
      <% @leftPick = @picks[(index/64)+60] %>
      <% @mpick = @mPicks[(index/64)+60] %>
      <% if @leftPick.nil? %>
        <td class=game id=wrong><%= "&nbsp;".html_safe %></td>
      <% else %>
        <td class=game
          <% if !@mpick.nil? %>
            <% if @leftPick.pick == @mpick.pick %>
              <%= 'id=correct' %>
            <% else %>
              <%= 'id=wrong' %>
            <% end %>
          <% end %>
        >
        <%= link_to @leftPick.pick, new_entry_pick_path(@entry, { :pick => @leftPick.pick, :round => @leftPick.round + 1, :game => @leftPick.game / 2 } ) %>
        </td>
      <% end %>
    <td></td>
      <% @rightPick = @picks[(index/64)+60+1] %>
      <% @mpick = @mPicks[(index/64)+60+1] %>
      <% if @rightPick.nil? %>
        <td class=game id=wrong><%= "&nbsp;".html_safe %></td>
      <% else %>
        <td class=game
          <% if !@mpick.nil? %>
            <% if @rightPick.pick == @mpick.pick %>
              <%= 'id=correct' %>
            <% else %>
              <%= 'id=wrong' %>
            <% end %>
          <% end %>
        >
        <%= link_to @rightPick.pick, new_entry_pick_path(@entry, { :pick => @rightPick.pick, :round => @rightPick.round + 1, :game => @rightPick.game / 2 } ) %>
        </td>
      <% end %>
    <td></td><td></td><td></td><td></td><td></td>
    </tr><tr><td>&nbsp;</td>
    </tr><tr>
    <td></td><td></td><td></td><td></td><td></td><td></td>
      <% if @picks[62].nil? %>
        <td class=game id=wrong><%= "&nbsp;".html_safe %></td>
      <% else %>
        <td class=game
          <% if !@mPicks[62].nil? %>
            <% if @picks[62].pick == @mPicks[62].pick %>
              <%= 'id=correct' %>
            <% else %>
              <%= 'id=wrong' %>
            <% end %>
          <% end %>
        >
        <%= @picks[62].pick %>
        </td>
      <% end %>
    <td></td><td></td><td></td><td></td><td></td><td></td>
    </tr><tr>
  <% end %>
  </tr>
<% end %>
</table>


<br />

<%= link_to 'Back', pool_entries_path(@pool) %>